[build]
  base = "client"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  NEXT_PUBLIC_API_URL = "https://your-railway-backend-url.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
