[build]
  base = "client"
  command = "npm install && NEXT_DISABLE_ESLINT_DURING_BUILD=true npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PUBLIC_API_URL = "https://iwanyu-store.onrender.com/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"
