services:
  # Backend API Service
  - type: web
    name: iwanyu-store
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run migrate && npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://iwanyu-frontend.onrender.com
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_ENCRYPTION_KEY
        sync: false

  # Frontend Next.js Service
  - type: web
    name: iwanyu-frontend
    env: node
    buildCommand: cd client && ./render-build.sh
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://iwanyu-store.onrender.com/api
